outdir: 'rl.11.2.0'
env: 'MineRLNavigate-v0'
world: 'CustomWorld_2'
logging_level: 20
interactor: no
downstream_task: no

seed: 0
gpu: 0

demo: yes
monitor: no
load: './results/train_rl.11.2.0/best/'
eval_n_runs: 200
sampling: 'weighted'

agent: 'CategoricalDoubleDQN'
arch: 'distributed_dueling'

max_episode_steps: 700
batch_size: 64
update_interval: 4
frame_skip: 10
gamma: 0.99
clip_delta: yes
num_step_return: 1
lr: 2.5e-4
adam_eps: 1.e-8

batch_accumulator: 'sum'
gray_scale: no
frame_stack: no

final_exploration_frames: 10.e+6
final_epsilon: 0.01
eval_epsilon: 0.001
noisy_net_sigma: null
replay_capacity: 10.e+6
replay_start_size: 1.e+4
prioritized: yes
target_update_interval: 2.e+4

encoder:
  type: 'vqvae'
  img_size: 64
  vqvae:
    encoder_version: 'vqvae_exp_1'
    load_epoch: 'mineRL/mlq3n3be/checkpoints/epoch=39-step=11679.ckpt'
    num_hiddens: 64
    num_residual_hiddens: 32
    num_residual_layers: 2
    embedding_dim: 256
    num_embeddings: 10
    commitment_cost: 0.25
    goals: [0,1,2,3,4,5,6,7,8,9]
  curl:
    encoder_version: 'curl_exp_0'
    load_epoch: 'mineRL/10d8jeqr/checkpoints/epoch=299-step=2099.ckpt'
    embedding_dim: 128
    path_goal_states: './goal_states/CT8_real_biome_curl_kmeans_10'
    goals: [0,1,2,3,4,5,6,7,8,9]
