eval:
	mkdir ../data/MineRLTreechop-v0/$(RES)
	cp ../data/MineRLTreechop-v0/base/* ../data/MineRLTreechop-v0/$(RES)/
	cp ./results/$(RES)/*.csv ../data/MineRLTreechop-v0/$(RES)/
	cp ./results/$(RES)/MineRLNavigate-v0/monitor/*.mp4 ../data/MineRLTreechop-v0/$(RES)/
