num: 1
x: 0
y: 64
z: 0
barrier: 50


# Mean and variance for normalizing input coordinates
coord:
  mean: [0.54113764, 64.52019, 5.4395313]
  var: [13.536015 ,  2.6483347, 12.29595]

#
# Diamond Block location. y coordinate will be overwrited by surface's y
#
dx: -16
dy: 0
dz: 14

# """
# Direction types:
#   'random': 360 possible directions
#   'single': 1 possible direction
#   'cardinal': north/south/west/east
# """

direction: 'random'  # random/single/discrete

# """
# random_position: False -> starts at (x,z)
# random_position: True -> starts at random position in range: (x-range, z-range) to (x+range, z+range)
# """

random_position: False
range: 45
